### ISSUE TITLE
Failed to load pack

### ISSUE THREAD

**Issue by ethaneee22** [Dystortedd/Ult-Effects#4]
Running Vanilla 1.21. It did end up loading when I deleted the `rendertype_entity_translucent_cull` files

`Caused by: aku: Invalid shaders/core/rendertype_entity_translucent_cull.json: Couldn't compile fragment program (file/Ultimate Effects v1.3, rendertype_entity_translucent_cull) : 3(86) : error C1102: incompatible type for parameter #1 ("topLeftCorner")
3(86) : error C1103: too few parameters in function call
3(97) : error C1102: incompatible type for parameter #1 ("topLeftCorner.88")
3(97) : error C1103: too few parameters in function call
	at aku.a(SourceFile:48) ~[minecraft-1.21-client.jar:?]
	at gfn.<init>(SourceFile:172) ~[minecraft-1.21-client.jar:?]
	at ges.c(SourceFile:497) ~[minecraft-1.21-client.jar:?]
	at ges$1.a(SourceFile:419) ~[minecraft-1.21-client.jar:?]
	at ges$1.a(SourceFile:396) ~[minecraft-1.21-client.jar:?]
	at auj.a(SourceFile:13) ~[minecraft-1.21-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more
Caused by: java.io.IOException: Couldn't compile fragment program (file/Ultimate Effects v1.3, rendertype_entity_translucent_cull) : 3(86) : error C1102: incompatible type for parameter #1 ("topLeftCorner")
3(86) : error C1103: too few parameters in function call
3(97) : error C1102: incompatible type for parameter #1 ("topLeftCorner.88")
3(97) : error C1103: too few parameters in function call
	at faw.b(SourceFile:69) ~[minecraft-1.21-client.jar:?]
	at faw.a(SourceFile:51) ~[minecraft-1.21-client.jar:?]
	at gfn.a(SourceFile:210) ~[minecraft-1.21-client.jar:?]
	at gfn.<init>(SourceFile:158) ~[minecraft-1.21-client.jar:?]
	at ges.c(SourceFile:497) ~[minecraft-1.21-client.jar:?]
	at ges$1.a(SourceFile:419) ~[minecraft-1.21-client.jar:?]
	at ges$1.a(SourceFile:396) ~[minecraft-1.21-client.jar:?]
	at auj.a(SourceFile:13) ~[minecraft-1.21-client.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 12 more`

**Comment by ethaneee22** [comment]
[Ultimate_Effects.zip](https://github.com/user-attachments/files/17494276/Ultimate_Effects.zip)

**Comment by Dystortedd** [comment]
will push a hotfix asap
